springdoc.api-docs.enabled=false
springdoc.swagger-ui.enabled=false

app.bootstrap.admin.enabled=${BOOTSTRAP_ADMIN_ENABLED:false}
app.bootstrap.admin.username=${BOOTSTRAP_ADMIN_USERNAME:}
app.bootstrap.admin.password=${BOOTSTRAP_ADMIN_PASSWORD:}
