package com.logistic.backend.audit;

public enum AuditEventType {
    REGISTER,
    REGISTRATION_APPROVED,
    REGISTRATION_REJECTED,
    ORDER_CREATED,
    ORDER_UPDATED,
    ORDER_COMPLETED,
    ORDER_REOPENED,
    ORDER_DELETED,
    DOCUMENTS_GENERATED,
    LOGIN
}
